// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4nRBaGcwLq6MlY-_SZvPl8RqwY5JfgzM',
    appId: '1:15647499849:web:954ddbf5fd358919844198',
    messagingSenderId: '15647499849',
    projectId: 'socialmediaapp-19b68',
    authDomain: 'socialmediaapp-19b68.firebaseapp.com',
    storageBucket: 'socialmediaapp-19b68.appspot.com',
    measurementId: 'G-NTBSRLFY19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnqCsQu_E45TYn9s433PxfahIl2KYxoRQ',
    appId: '1:15647499849:android:25598393cdea3e09844198',
    messagingSenderId: '15647499849',
    projectId: 'socialmediaapp-19b68',
    storageBucket: 'socialmediaapp-19b68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaghkEbLnAWwdg1mAhvE5PvatHZMvmAxE',
    appId: '1:15647499849:ios:ccdceb49a91f7f91844198',
    messagingSenderId: '15647499849',
    projectId: 'socialmediaapp-19b68',
    storageBucket: 'socialmediaapp-19b68.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
